jwt:
  secret: secretkeyteamprojectAiProMJUsecretkeyteamprojectAiProMJUsecretkeyteamprojectAiProMJUsecretkeyteamprojectAiProMJU
#spring:
#  datasource:
#    url: jdbc:mysql://ai-pro-db.cfkgmyscawu5.ap-northeast-2.rds.amazonaws.com:3306/aipro
#    username: aipro
#    password: aiprodb!!!
#    driver-class-name: com.mysql.cj.jdbc.Driver
spring:
  datasource:
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
