jwt:
  secret: secretkeyteamprojectAiProMJUsecretkeyteamprojectAiProMJUsecretkeyteamprojectAiProMJUsecretkeyteamprojectAiProMJU
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/std
    username: user
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  # datasource:
  #   url: ${MYSQL_URL}
  #   username: ${MYSQL_USERNAME}
  #   password: ${MYSQL_PASSWORD}
  #   driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
ai:
  uri: http://15.165.114.217:5000/query
